### ISSUE TITLE
Lab 7

### ISSUE THREAD

**Issue by ghost** [guptaanmol184/OOAD-LAB-2017#2]
Please put down the problems you are taking up here.
So, that multiple people don't work on same problem.
@guptaanmol184 @srikrishna0130 Saravana

**Comment by srikrishna0130** [comment]
I am doing the ap question for now and
the last question also

**Comment by srikrishna0130** [comment]
@guptaanmol184 Please add user @gsbalaji2011 to contributors list.

**Comment by guptaanmol184** [comment]
Already added.
He has to accept the invite.
@gsbalaji2011 accept the invite

![64bc5bcb-9a30-4eb2-9ccc-a60387b1c97e](https://cloud.githubusercontent.com/assets/18148655/24781624/8fb7d6fc-1b5e-11e7-8857-8542d95b63f9.jpg)
